Gothsec/StockIn

client/src/components/Login.jsx
server/controllers/product/addProductController.js
server/controllers/product/readProductsController.js
server/controllers/product/removeProductController.js

[fix] db route import on product controllers

---

client/src/components/ForgotPassword.jsx
client/src/components/Login.jsx

Modal window added at Login.jsx component

Password recovery modal window

---

client/src/components/orders/OrderRow.jsx
client/src/pages/Orders.jsx
server/api/endPoints.js
server/controllers/order/readOrderController.js

Implemented Orders Page with Orders List

---

client/src/components/ModalWindows.jsx
client/src/components/ProductFile.jsx
index.js
server/api/endPoints.js
server/controllers/product/addProductController.js
server/controllers/product/updateProductController.js

it still needs to add dynamic warehouse and supplier inputs.
✔

[modification] added validations and modified modalWindows.

---

client/src/components/ForgotPassword.jsx
index.js
node_modules/.package-lock.json
package-lock.json
package.json
server/api/endPoints.js
server/controllers/passwordrecovery/authController.js
server/controllers/passwordrecovery/mailService.js
server/models/userModel.js
stockin.sql

Two new modules to install:
- npm i dotenv nodemailer

Forgot password module

---

client/src/assets/OrdersIcon.jsx
client/src/components/Nav.jsx
client/src/pages/Home.jsx
client/src/pages/Orders.jsx
server/api/endPoints.js
server/controllers/order/addOrderController.js
server/controllers/order/readOrderController.js

Orders icon on navbar

---

client/src/components/orders/CreateOrderModal.jsx
server/controllers/order/addOrderController.js

Create order modal backend

---

client/src/components/orders/OrderRow.jsx
client/src/components/orders/ReadUpdateOrderModal.jsx
index.js
server/api/endPoints.js
server/controllers/order/getOrderByIdController.js
server/controllers/order/readOrderController.js
server/controllers/order/updateOrderController.js

**Thanks to @Gothsec for helping me with this 🤦‍♂️**
*I'm free*

[Add] Reading and updating functionallity to orders 🤠

---

client/src/components/orders/CreateOrderModal.jsx
server/controllers/order/addOrderController.js

[Add] state = active on _order table and reload window

---

client/src/components/ForgotPassword.jsx

[Add] await button useState to send link

---

client/src/components/ForgotPassword.jsx
client/src/components/ResetPassword.jsx
server/api/endPoints.js
server/controllers/passwordrecovery/authController.js
server/controllers/passwordrecovery/mailService.js

[Feature] Reset password working on db, no frontend added

---

client/src/components/ModalWindows.jsx
client/src/components/ProductRow.jsx
client/src/components/orders/CreateOrderModal.jsx
client/src/components/orders/ReadUpdateOrderModal.jsx
client/src/pages/Home.jsx
server/controllers/order/addOrderController.js
server/controllers/order/getOrderByIdController.js
server/controllers/order/readOrderController.js
server/controllers/order/removeOrderController.js
server/controllers/order/updateOrderController.js
server/controllers/product/addProductController.js
server/controllers/product/editProductController.js
server/controllers/product/eliminationProductController.js
server/controllers/product/readProductsController.js

There's no endpoint for the edit product function
@1Orchestratooor1

[Change] Querys updated

---

client/src/components/Nav.jsx

[Fix] Navbar responsive

---

client/src/components/Nav.jsx

Better interaction from medium than small devices

Change from sm (small) to md (medium) devices

---

client/src/components/Nav.jsx

[Fix] Resposive width change

---

client/src/components/ModalWindows.jsx
client/src/components/ProductRow.jsx
server/api/endPoints.js
server/controllers/product/editProductController.js

[Fix] Validations and 'update products' function fixed

---

client/src/components/Nav.jsx
client/src/pages/Home.jsx
client/src/pages/Orders.jsx
client/src/pages/Products.jsx

Also changed a little bit the view, the responsiveness is not finished (1/2)

Refactored Nav component, added into Home

---

client/src/App.jsx
client/src/components/Nav.jsx
client/src/pages/Home.jsx

[Change] Returning to the previous code for avoid mistakes

---

client/src/components/ProductRow.jsx
client/src/components/orders/OrderRow.jsx
client/src/pages/Orders.jsx
client/src/pages/Products.jsx

v1 frontend to better usability

Products and Orders pages with better UI

---

server/controllers/passwordrecovery/authController.js

Couldn't did it with a jsx component bc is on Server Sider rendering

[Style] Reset password page with better UI

---

client/src/components/Nav.jsx
client/src/pages/Home.jsx

[Fix] Navigation function with href

---

client/src/components/Login.jsx

Better UI and Remember-me checkbox 🎨

[Style] Better UI and Remember-me checkbox

---

client/src/components/orders/ButtonUpdate.jsx
client/src/components/orders/ModalOrder.jsx

Fixed to send the new info into the order and closing the modal window

[Fix] Updating order button fixed

---

client/src/components/orders/ModalOrder.jsx

Show deleted products list on Order modal

[Fix] Show deleted products list on Order modal

---

client/src/components/MessageConfirmation.jsx
client/src/components/orders/ButtonCreate.jsx
client/src/components/products/ButtonCreate.jsx
client/src/components/suppliers/ButtonCreateSupplier.jsx

[Change] Change position and z-index to error notification

[Add] Add validation for create product, order and supplier

---

client/src/components/Login.jsx

Validation to check if the user's state is TRUE in the user table

[Fix] Validate user state before login

---

client/src/components/orders/OrderRow.jsx
client/src/components/suppliers/SupplierRow.jsx
client/src/pages/Orders.jsx
client/src/pages/Supplier.jsx

UI styles (Order and Supplier pages)

---

client/src/main.jsx
client/src/pages/Home.jsx
client/src/pages/NotFound.jsx
client/src/styles.css

[Style] Page Notfound v1

---

client/src/components/moves/ModalMove.jsx
client/src/components/products/ModalProduct.jsx
client/src/components/suppliers/ModalSupplier.jsx
client/src/components/warehouses/ModalWarehouse.jsx

[Change] Changed info modal for each entity

---

client/src/components/moves/MoveRow.jsx
client/src/components/warehouses/WarehouseRow.jsx
client/src/pages/Moves.jsx
client/src/pages/Products.jsx
client/src/pages/Supplier.jsx
client/src/pages/Warehouse.jsx

Consistency UI

---

client/src/components/dashboard/TotalProductsCard.jsx
client/src/pages/Dashboard.jsx

It sums total quantity for each product on stock

[Add] Dashboard Total Products card

---

client/src/components/dashboard/FinancialOverviewCard.jsx
client/src/components/dashboard/TotalCostCard.jsx
client/src/components/dashboard/TotalGainCard.jsx
client/src/components/dashboard/TotalProductsCard.jsx
client/src/components/dashboard/TotalPublicPriceCard.jsx
client/src/pages/Dashboard.jsx

[Add] Total public price + Total cost + Total gain cards

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/components/dashboard/MovesBarChart.jsx
client/src/pages/Dashboard.jsx

[Add] Barchart by moves on dashboard

---

client/src/pages/Home.jsx

[Fix] Employees page

---

client/src/components/moves/ModalMove.jsx

[Add] Added 'filter product' input to improve its selection process

---

client/src/components/Login.jsx
client/src/pages/Signin.jsx

I think is a temporal solution

[Fix] Login bug reload window
